package com.akka.test.node.handler.bean;

public enum HandlerType {

    TRIGGER_DEVICE_MESSAGE,
    TRIGGER_GROUP_MESSAGE,
    TRIGGER_TASK,
    FILTER_TIMEFREQUENCY,
    FILTER_DEVICECONNECTSTATE,
    FILTER_TIMERANGE,
    FILTER_DATETIMERANGE,
    FILTER_DEVICE_MESSAGE,
    ACTION_SEND_DEVICEMSG,
    ACTION_ALARM,



}
